FROM node:18-bullseye-slim

RUN apt-get update && apt-get install -y \
    ffmpeg fonts-liberation libasound2 libnss3 libxss1 libxtst6 xdg-utils \
    --no-install-recommends && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npx puppeteer browsers install chrome

COPY . .
EXPOSE 3000
CMD ["node", "server.js"]